clc;
clear all;
close all;
oversampling_Factor=8;
Input_bit=[1];
Input_bit_os=upsample(Input_bit,overSampling_Factor);
alpha=0.1;
pt=srrc(overSampling_Factor,alpha);
figure;
stem(pt);
output_of_srrc_filter=conv(input_bit_os,pt);
figure;
stem(output_of_srrc_filter=awgn(output_of_srrc_filter,100));
title('response of SRRC_filter at Tx side');
xlabel('samples');
ylabel('amplitude');
y=conv(output_of_srrc_filter,pt);
figure;
stem(y);
title('matched filter(SRRC)response at Rx side');
xlabel('samples');
ylabel('amplitude');
midsample=length(-4:1/oversampling_factor:4);
y down=downsample(y,oversampling_factor,1);
figure;
stem(y_down);
title('down sampled output(ADC conversion and sampling)');
xlabel('samples');
ylabel('amplitude');
